resources:
      
  - name: vijayRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/powershell
      
pipelines:
  - name: vijay_pipeline
    steps:  
      - name: functions
        type: PowerShell
        configuration:
          nodePool: win_2019     
          integrations:
            - name: vijay
            - name: slack          
          inputResources:
            - name: vijayRepo


        execution:
          onExecute:
            - find_resource_variable myRepo $res_vijayRepo_resourcePath
            - send_notification slack
#             - replicate_resource myTestImage myStageImage
            - $testvariable
            - $vijay
            #pipelines
            - get-childitem $res_vijayRepo_resourcePath
            - Push-Location $res_vijayRepo_resourcePath
            - get-childitem $step_tmp_dir  
            - add_run_files -sources "$res_myRepo_resourcePath" -name vijayRepo   
            - add_pipeline_files -sources "$res_vijayRepo_resourcePath" -name vijay    
                      
      - name: functions2
        type: PowerShell
        configuration:
          nodePool: win_2019             
          inputSteps:
            - name: functions
        execution:
          onExecute:
            - get-childitem $res_vijayRepo_resourcePath    
            - restore_run_files -name vijayRepo -path $step_tmp_dir   
            - get-childitem $res_vijayRepo_resourcePath    
            - echo $pipelineVariable                        
            - echo $runVariable       
            
      - name: functions3
        type: PowerShell
        configuration:   
          nodePool: win_2019         
          inputSteps:
            - name: functions2
        execution:
          onExecute:
            - get-childitem $res_vijayRepo_resourcePath    
            - echo $pipelineVariable                       
            - restore_pipeline_files -name vijay -path $step_tmp_dir
            - get-childitem $step_tmp_dir   
            - echo $runVariable            
            

            
