resources:
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/powershell
pipelines:
  - name: vijay_pipeline
    steps:  
      - name: functions
        type: PowerShell 
        configuration:
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - Push-Location $res_myRepo_resourcePath
            - get-childitem $res_myRepo_resourcePath
            - find_resource_variable myRepo $res_myRepo_resourcePath
            - New-Item -Path 'C:\Users\Administrator\Downloads\hello.txt' -ItemType File 
            - Set-Content -Path "C:\Users\Administrator\Downloads\hello.txt" -Value "My Value" -Force 
            - add_run_files -sources "C:\Users\Administrator\Downloads\hello.txt" -name repo_pipe   
            - add_pipeline_files -sources "C:\Users\Administrator\Downloads\hello.txt" -name vijay                
      - name: functions2
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath    
            - restore_run_files -name repo_pipe -path "C:\Users\Administrator\Downloads\hello.txt"   
            - get-childitem $res_myRepo_resourcePath  
            - get-content C:\Users\Administrator\Downloads\hello.txt
      - name: functions3
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions2
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath                        
            - restore_pipeline_files -name vijay -path "C:\Users\Administrator\Downloads\hello.txt"
            - get-childitem $res_myRepo_resourcePath 
            - get-content C:\Users\Administrator\Downloads\hello.txt
