resources:
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/powershell
pipelines:
  - name: vijay_pipeline
    configuration:
      nodePool: aws_windows
    steps:  
      - name: functions
        type: PowerShell 
        configuration:
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - Push-Location $res_myRepo_resourcePath
            - get-childitem $res_myRepo_resourcePath
            - get-childitem $step_tmp_dir
            - bump_semver v3.0.0 major
            - bump_semver v3.0.0 minor
            - bump_semver v3.0.0 patch
            - bump_semver v3.0.0 beta  
#             - retry_command printen
#             - replace_envs "$res_myRepo_resourcePath\keys" 
            - $env:tempPath = $env:Path
            - $env:Path = $env:Path + ';' + ((Get-Command git).Path -replace 'cmd\\git\.exe$','usr\bin')
            - echo $env:Path  
            - execute_command Get-Host
            - compare_git -Path "$res_myRepo_resourcePath" -commit-range master..HEAD~4 
            - compare_git -Path "$res_myRepo_resourcePath" -commit-range master..HEAD~4 | Foreach ($file) { Write-Output "pipelines.yml"} 
            - compare_git -Path "$res_myRepo_resourcePath" -commit-range master..HEAD~4 -depth 2
            - compare_git myRepo -commit-range master..HEAD~4 -directories-only
            - compare_git myRepo -commit-range master..HEAD~4 -directories-only -depth 2
            - Set-Content -Path "test.json" -Value "{'username':'Test','attachments':[{'pretext':'This is','text':'to test','color':'#5183a0'}],'icon_url':'${opt_icon_url}'}"
#             - read_json -Path "$res_myRepo_resourcePath\test.json" "username"
#             - update_commit_status myRepo -context "Windows" -message "testing step $step_id" -status failure
            - update_commit_status myRepo -context "Windows" -message "testing step $step_id" -status failure      
            - add_run_variables testvariable="asdffdjksfjk.    1"
            - add_run_variables "scm=gitRepo" 'runVariable1="A string with spaces."' runVariable2='A string with $.'
            - add_pipeline_variables vijay="kumar.      1"   
            - add_pipeline_variables "scm=gitRepo" 'runVariable1="A string with spaces."' runVariable2='A string with $.'
#             - send_notification slack
            - $testvariable
            - $vijay
            - Get-Variable | format-table
            - write_output winAuto_image "imageTag=$run_id"    
            - choco install python3
            - python --version
            - python -m pip install --upgrade pip
            - pip --version
            - pip install pytest
            - pytest --version
            - Push-Location $res_myRepo_resourcePath
            - get-childitem $res_myRepo_resourcePath
            #- pytest tests/test_sample.py
            - py.test --verbose --junit-xml test-reports/results.xml test_sample.py       
            - Get-Content -Path test-reports/results.xml
            - save_tests test-reports/results.xml      
            - add_run_variables "scm=gitRepo" 'runVariable1="A string with spaces."' runVariable2='A string with $.'
            - add_run_variables "scm=gitRepo"
            - export_run_variables "windows=poweshell"
            - add_pipeline_variables "scm=s_gitHub"
            - export_pipeline_variables "jfrog=pipelines"  
            
            - get-childitem $res_myRepo_resourcePath
            - find_resource_variable myRepo $res_myRepo_resourcePath
            - New-Item -Path 'C:\Users\Administrator\Downloads\hello.txt' -ItemType File 
            - Set-Content -Path "C:\Users\Administrator\Downloads\hello.txt" -Value "My Value" -Force 
            - add_run_files -sources "C:\Users\Administrator\Downloads\hello.txt" -name repo_pipe   
            - add_pipeline_files -sources "C:\Users\Administrator\Downloads\hello.txt" -name vijay        
            
            
      - name: functions2
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath    
            - restore_run_files -name repo_pipe -path "C:\Users\Administrator\Downloads\hello.txt"   
            - get-childitem $res_myRepo_resourcePath  
            - get-content C:\Users\Administrator\Downloads\hello.txt
            - echo $pipelineVariable                        
            - echo $runVariable              
            
      - name: functions3
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions2
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath                        
            - restore_pipeline_files -name vijay -path "C:\Users\Administrator\Downloads\hello.txt"
            - get-childitem $res_myRepo_resourcePath 
            - get-content C:\Users\Administrator\Downloads\hello.txt
            - echo $pipelineVariable                        
            - echo $runVariable  
