pipelines:
  - name: vijay_pipeline
    steps:  
      - name: functions
        type: PowerShell
#         type: Bash        
        configuration:
          nodePool: win_2019        
        execution:
          onExecute:
            - echo "test"         
