pipelines:
  - name: vijay_pipeline
    steps:  
      - name: functions
        type: PowerShell
        configuration:
          nodePool: win_2019        
        execution:
          onExecute:
            - echo "test"         
